version: '3.1'

volumes:
  postgres_data_facebookDB:

services:
  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: facebookDB
      POSTGRES_USER: mehedi
      POSTGRES_PASSWORD: mehedi
    volumes:
      - postgres_data_facebookDB:/var/lib/postgresql/data
    ports:
      - '5432:5432'
